resource "iosxr_hw_module_profile" "hw_module_profile" {
  for_each                                                     = { for device in local.devices : device.name => device if try(local.device_config[device.name].hw_module_profile, null) != null || try(local.defaults.iosxr.devices.configuration.hw_module_profile, null) != null }
  device                                                       = each.value.name
  profile_load_balance_algorithm_hash_polynomial_index         = try(local.device_config[each.value.name].hw_module_profile.profile_load_balance_algorithm_hash_polynomial_index, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_load_balance_algorithm_hash_polynomial_index, null)
  profile_load_balance_algorithm_fat_based_hash                = try(local.device_config[each.value.name].hw_module_profile.profile_load_balance_algorithm_fat_based_hash, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_load_balance_algorithm_fat_based_hash, null)
  profile_load_balance_algorithm_gtp                           = try(local.device_config[each.value.name].hw_module_profile.profile_load_balance_algorithm_gtp, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_load_balance_algorithm_gtp, null)
  profile_load_balance_algorithm_gtp_mpls                      = try(local.device_config[each.value.name].hw_module_profile.profile_load_balance_algorithm_gtp_mpls, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_load_balance_algorithm_gtp_mpls, null)
  profile_load_balance_algorithm_inner_l2_field                = try(local.device_config[each.value.name].hw_module_profile.profile_load_balance_algorithm_inner_l2_field, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_load_balance_algorithm_inner_l2_field, null)
  profile_load_balance_algorithm_ip_tunnel                     = try(local.device_config[each.value.name].hw_module_profile.profile_load_balance_algorithm_ip_tunnel, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_load_balance_algorithm_ip_tunnel, null)
  profile_load_balance_algorithm_l3_only                       = try(local.device_config[each.value.name].hw_module_profile.profile_load_balance_algorithm_l3_only, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_load_balance_algorithm_l3_only, null)
  profile_load_balance_algorithm_layer2                        = try(local.device_config[each.value.name].hw_module_profile.profile_load_balance_algorithm_layer2, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_load_balance_algorithm_layer2, null)
  profile_load_balance_algorithm_mpls_lsr_ler                  = try(local.device_config[each.value.name].hw_module_profile.profile_load_balance_algorithm_mpls_lsr_ler, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_load_balance_algorithm_mpls_lsr_ler, null)
  profile_load_balance_algorithm_mpls_lsr_ler_optimized        = try(local.device_config[each.value.name].hw_module_profile.profile_load_balance_algorithm_mpls_lsr_ler_optimized, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_load_balance_algorithm_mpls_lsr_ler_optimized, null)
  profile_load_balance_algorithm_mpls_safe_speculative_parsing = try(local.device_config[each.value.name].hw_module_profile.profile_load_balance_algorithm_mpls_safe_speculative_parsing, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_load_balance_algorithm_mpls_safe_speculative_parsing, null)
  profile_load_balance_algorithm_pppoe                         = try(local.device_config[each.value.name].hw_module_profile.profile_load_balance_algorithm_pppoe, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_load_balance_algorithm_pppoe, null)
  profile_load_balance_algorithm_pppoe_decap_fatbased_hashing  = try(local.device_config[each.value.name].hw_module_profile.profile_load_balance_algorithm_pppoe_decap_fatbased_hashing, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_load_balance_algorithm_pppoe_decap_fatbased_hashing, null)
  profile_bundle_hash_ignore_ingress_port                      = try(local.device_config[each.value.name].hw_module_profile.profile_bundle_hash_ignore_ingress_port, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_bundle_hash_ignore_ingress_port, null)
  profile_bundle_hash_per_packet_round_robin                   = try(local.device_config[each.value.name].hw_module_profile.profile_bundle_hash_per_packet_round_robin, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_bundle_hash_per_packet_round_robin, null)
  profile_qos_max_classmap_size                                = try(local.device_config[each.value.name].hw_module_profile.profile_qos_max_classmap_size, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_qos_max_classmap_size, null)
  profile_qos_qosg_dscp_mark_enable_first                      = try(local.device_config[each.value.name].hw_module_profile.profile_qos_qosg_dscp_mark_enable_first, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_qos_qosg_dscp_mark_enable_first, null)
  profile_qos_qosg_dscp_mark_enable_second                     = try(local.device_config[each.value.name].hw_module_profile.profile_qos_qosg_dscp_mark_enable_second, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_qos_qosg_dscp_mark_enable_second, null)
  profile_qos_free_buffer_int_threshold_set                    = try(local.device_config[each.value.name].hw_module_profile.profile_qos_free_buffer_int_threshold_set, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_qos_free_buffer_int_threshold_set, null)
  profile_qos_free_buffer_int_threshold_clear                  = try(local.device_config[each.value.name].hw_module_profile.profile_qos_free_buffer_int_threshold_clear, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_qos_free_buffer_int_threshold_clear, null)
  profile_qos_hqos_enable                                      = try(local.device_config[each.value.name].hw_module_profile.profile_qos_hqos_enable, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_qos_hqos_enable, null)
  profile_qos_stats_collection                                 = try(local.device_config[each.value.name].hw_module_profile.profile_qos_stats_collection, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_qos_stats_collection, null)
  profile_qos_ecn_marking_stats                                = try(local.device_config[each.value.name].hw_module_profile.profile_qos_ecn_marking_stats, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_qos_ecn_marking_stats, null)
  profile_qos_shared_policer_per_class_stats                   = try(local.device_config[each.value.name].hw_module_profile.profile_qos_shared_policer_per_class_stats, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_qos_shared_policer_per_class_stats, null)
  profile_qos_wred_stats_enable                                = try(local.device_config[each.value.name].hw_module_profile.profile_qos_wred_stats_enable, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_qos_wred_stats_enable, null)
  profile_qos_lag_scheduler                                    = try(local.device_config[each.value.name].hw_module_profile.profile_qos_lag_scheduler, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_qos_lag_scheduler, null)
  profile_qos_conform_aware_policer                            = try(local.device_config[each.value.name].hw_module_profile.profile_qos_conform_aware_policer, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_qos_conform_aware_policer, null)
  profile_qos_arp_isis_priority_enable                         = try(local.device_config[each.value.name].hw_module_profile.profile_qos_arp_isis_priority_enable, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_qos_arp_isis_priority_enable, null)
  profile_qos_gre_exp_classification_enable                    = try(local.device_config[each.value.name].hw_module_profile.profile_qos_gre_exp_classification_enable, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_qos_gre_exp_classification_enable, null)
  profile_qos_egress_compensation_setting_force                = try(local.device_config[each.value.name].hw_module_profile.profile_qos_egress_compensation_setting_force, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_qos_egress_compensation_setting_force, null)
  profile_qos_policer_scale                                    = try(local.device_config[each.value.name].hw_module_profile.profile_qos_policer_scale, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_qos_policer_scale, null)
  profile_qos_nif_hp_fifo_reserve_percent                      = try(local.device_config[each.value.name].hw_module_profile.profile_qos_nif_hp_fifo_reserve_percent, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_qos_nif_hp_fifo_reserve_percent, null)
  netflow_ipfix315_enable                                      = try(local.device_config[each.value.name].hw_module_profile.netflow_ipfix315_enable, local.defaults.iosxr.devices.configuration.hw_module_profile.netflow_ipfix315_enable, null)
  netflow_sflow_enable                                         = try(local.device_config[each.value.name].hw_module_profile.netflow_sflow_enable, local.defaults.iosxr.devices.configuration.hw_module_profile.netflow_sflow_enable, null)
  npu_native_mode_enable                                       = try(local.device_config[each.value.name].hw_module_profile.npu_native_mode_enable, local.defaults.iosxr.devices.configuration.hw_module_profile.npu_native_mode_enable, null)
  oam_four8byte_cfm_maid_enable                                = try(local.device_config[each.value.name].hw_module_profile.oam_four8byte_cfm_maid_enable, local.defaults.iosxr.devices.configuration.hw_module_profile.oam_four8byte_cfm_maid_enable, null)
  oam_sat_enable                                               = try(local.device_config[each.value.name].hw_module_profile.oam_sat_enable, local.defaults.iosxr.devices.configuration.hw_module_profile.oam_sat_enable, null)
  offload_one                                                  = try(local.device_config[each.value.name].hw_module_profile.offload_one, local.defaults.iosxr.devices.configuration.hw_module_profile.offload_one, null)
  offload_two                                                  = try(local.device_config[each.value.name].hw_module_profile.offload_two, local.defaults.iosxr.devices.configuration.hw_module_profile.offload_two, null)
  offload_three                                                = try(local.device_config[each.value.name].hw_module_profile.offload_three, local.defaults.iosxr.devices.configuration.hw_module_profile.offload_three, null)
  offload_four                                                 = try(local.device_config[each.value.name].hw_module_profile.offload_four, local.defaults.iosxr.devices.configuration.hw_module_profile.offload_four, null)
  stats_acl_permit                                             = try(local.device_config[each.value.name].hw_module_profile.stats_acl_permit, local.defaults.iosxr.devices.configuration.hw_module_profile.stats_acl_permit, null)
  stats_enhanced_sr_policy                                     = try(local.device_config[each.value.name].hw_module_profile.stats_enhanced_sr_policy, local.defaults.iosxr.devices.configuration.hw_module_profile.stats_enhanced_sr_policy, null)
  stats_ingress_sr                                             = try(local.device_config[each.value.name].hw_module_profile.stats_ingress_sr, local.defaults.iosxr.devices.configuration.hw_module_profile.stats_ingress_sr, null)
  stats_ingress_sr_mspw                                        = try(local.device_config[each.value.name].hw_module_profile.stats_ingress_sr_mspw, local.defaults.iosxr.devices.configuration.hw_module_profile.stats_ingress_sr_mspw, null)
  stats_qos_enhanced                                           = try(local.device_config[each.value.name].hw_module_profile.stats_qos_enhanced, local.defaults.iosxr.devices.configuration.hw_module_profile.stats_qos_enhanced, null)
  stats_tx_scale_enhanced                                      = try(local.device_config[each.value.name].hw_module_profile.stats_tx_scale_enhanced, local.defaults.iosxr.devices.configuration.hw_module_profile.stats_tx_scale_enhanced, null)
  stats_tx_scale_enhanced_acl_permit                           = try(local.device_config[each.value.name].hw_module_profile.stats_tx_scale_enhanced_acl_permit, local.defaults.iosxr.devices.configuration.hw_module_profile.stats_tx_scale_enhanced_acl_permit, null)
  stats_tx_scale_enhanced_ingress_sr                           = try(local.device_config[each.value.name].hw_module_profile.stats_tx_scale_enhanced_ingress_sr, local.defaults.iosxr.devices.configuration.hw_module_profile.stats_tx_scale_enhanced_ingress_sr, null)
  stats_tx_scale_enhanced_qos_enhanced                         = try(local.device_config[each.value.name].hw_module_profile.stats_tx_scale_enhanced_qos_enhanced, local.defaults.iosxr.devices.configuration.hw_module_profile.stats_tx_scale_enhanced_qos_enhanced, null)
  srv6_mode_base                                               = try(local.device_config[each.value.name].hw_module_profile.srv6_mode_base, local.defaults.iosxr.devices.configuration.hw_module_profile.srv6_mode_base, null)
  srv6_mode_base_and_micro_segment_f3216                       = try(local.device_config[each.value.name].hw_module_profile.srv6_mode_base_and_micro_segment_f3216, local.defaults.iosxr.devices.configuration.hw_module_profile.srv6_mode_base_and_micro_segment_f3216, null)
  srv6_mode_micro_segment_format_f3216                         = try(local.device_config[each.value.name].hw_module_profile.srv6_mode_micro_segment_format_f3216, local.defaults.iosxr.devices.configuration.hw_module_profile.srv6_mode_micro_segment_format_f3216, null)
  srv6_mode_micro_segment_format_f3216_path_mtu                = try(local.device_config[each.value.name].hw_module_profile.srv6_mode_micro_segment_format_f3216_path_mtu, local.defaults.iosxr.devices.configuration.hw_module_profile.srv6_mode_micro_segment_format_f3216_path_mtu, null)
  srv6_encapsulation_l2_traffic_class_propagate                = try(local.device_config[each.value.name].hw_module_profile.srv6_encapsulation_l2_traffic_class_propagate, local.defaults.iosxr.devices.configuration.hw_module_profile.srv6_encapsulation_l2_traffic_class_propagate, null)
  srv6_encapsulation_l2_traffic_class_value                    = try(local.device_config[each.value.name].hw_module_profile.srv6_encapsulation_l2_traffic_class_value, local.defaults.iosxr.devices.configuration.hw_module_profile.srv6_encapsulation_l2_traffic_class_value, null)
  srv6_encapsulation_l3_traffic_class_propagate                = try(local.device_config[each.value.name].hw_module_profile.srv6_encapsulation_l3_traffic_class_propagate, local.defaults.iosxr.devices.configuration.hw_module_profile.srv6_encapsulation_l3_traffic_class_propagate, null)
  srv6_encapsulation_l3_traffic_class_policy_map               = try(local.device_config[each.value.name].hw_module_profile.srv6_encapsulation_l3_traffic_class_policy_map, local.defaults.iosxr.devices.configuration.hw_module_profile.srv6_encapsulation_l3_traffic_class_policy_map, null)
  srv6_encapsulation_l3_traffic_class_value                    = try(local.device_config[each.value.name].hw_module_profile.srv6_encapsulation_l3_traffic_class_value, local.defaults.iosxr.devices.configuration.hw_module_profile.srv6_encapsulation_l3_traffic_class_value, null)
  srv6_encapsulation_l3_traffic_class_with_hoplimit_propagate  = try(local.device_config[each.value.name].hw_module_profile.srv6_encapsulation_l3_traffic_class_with_hoplimit_propagate, local.defaults.iosxr.devices.configuration.hw_module_profile.srv6_encapsulation_l3_traffic_class_with_hoplimit_propagate, null)
  sr_policy_v6_null_label_autopush                             = try(local.device_config[each.value.name].hw_module_profile.sr_policy_v6_null_label_autopush, local.defaults.iosxr.devices.configuration.hw_module_profile.sr_policy_v6_null_label_autopush, null)
  fib_bgp_pic_multipath_core_enable                            = try(local.device_config[each.value.name].hw_module_profile.fib_bgp_pic_multipath_core_enable, local.defaults.iosxr.devices.configuration.hw_module_profile.fib_bgp_pic_multipath_core_enable, null)
  bgp_mp_pic_auto_protect_enable                               = try(local.device_config[each.value.name].hw_module_profile.bgp_mp_pic_auto_protect_enable, local.defaults.iosxr.devices.configuration.hw_module_profile.bgp_mp_pic_auto_protect_enable, null)

  profile_qos_max_classmap_size_locations = try(length(local.device_config[each.value.name].hw_module_profile.profile_qos_max_classmap_size_locations) == 0, true) ? null : [for location in local.device_config[each.value.name].hw_module_profile.profile_qos_max_classmap_size_locations : {
    location_name     = try(location.location_name, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_qos_max_classmap_size_locations.location_name, null)
    max_classmap_size = try(location.max_classmap_size, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_qos_max_classmap_size_locations.max_classmap_size, null)
    }
  ]

  profile_qos_nif_hp_fifo_reserve_locations = try(length(local.device_config[each.value.name].hw_module_profile.profile_qos_nif_hp_fifo_reserve_locations) == 0, true) ? null : [for location in local.device_config[each.value.name].hw_module_profile.profile_qos_nif_hp_fifo_reserve_locations : {
    location_name = try(location.location_name, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_qos_nif_hp_fifo_reserve_locations.location_name, null)
    percent       = try(location.percent, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_qos_nif_hp_fifo_reserve_locations.percent, null)
    }
  ]

  profile_bundle_hash_index_locations = try(length(local.device_config[each.value.name].hw_module_profile.profile_bundle_hash_index_locations) == 0, true) ? null : [for location in local.device_config[each.value.name].hw_module_profile.profile_bundle_hash_index_locations : {
    location_name  = try(location.location_name, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_bundle_hash_index_locations.location_name, null)
    location_name2 = try(location.location_name2, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_bundle_hash_index_locations.location_name2, null)
    index          = try(location.index, local.defaults.iosxr.devices.configuration.hw_module_profile.profile_bundle_hash_index_locations.index, null)
    }
  ]

  netflow_ipfix315_enable_locations = try(length(local.device_config[each.value.name].hw_module_profile.netflow_ipfix315_enable_locations) == 0, true) ? null : [for location in local.device_config[each.value.name].hw_module_profile.netflow_ipfix315_enable_locations : {
    location_name  = try(location.location_name, local.defaults.iosxr.devices.configuration.hw_module_profile.netflow_ipfix315_enable_locations.location_name, null)
    location_name2 = try(location.location_name2, local.defaults.iosxr.devices.configuration.hw_module_profile.netflow_ipfix315_enable_locations.location_name2, null)
    }
  ]

  netflow_sflow_enable_locations = try(length(local.device_config[each.value.name].hw_module_profile.netflow_sflow_enable_locations) == 0, true) ? null : [for location in local.device_config[each.value.name].hw_module_profile.netflow_sflow_enable_locations : {
    location_name  = try(location.location_name, local.defaults.iosxr.devices.configuration.hw_module_profile.netflow_sflow_enable_locations.location_name, null)
    location_name2 = try(location.location_name2, local.defaults.iosxr.devices.configuration.hw_module_profile.netflow_sflow_enable_locations.location_name2, null)
    }
  ]
}
