resource "iosxr_line_default" "line_default" {
  for_each                    = { for device in local.devices : device.name => device if try(local.device_config[device.name].line_default, null) != null || try(local.defaults.iosxr.devices.configuration.line_default, null) != null }
  device                      = each.value.name
  autocommand                 = try(local.device_config[each.value.name].line_default.autocommand, local.defaults.iosxr.devices.configuration.line_default.autocommand, null)
  access_class_ingress        = try(local.device_config[each.value.name].line_default.access_class_ingress, local.defaults.iosxr.devices.configuration.line_default.access_class_ingress, null)
  access_class_egress         = try(local.device_config[each.value.name].line_default.access_class_egress, local.defaults.iosxr.devices.configuration.line_default.access_class_egress, null)
  disconnect_character        = try(local.device_config[each.value.name].line_default.disconnect_character, local.defaults.iosxr.devices.configuration.line_default.disconnect_character, null)
  escape_character            = try(local.device_config[each.value.name].line_default.escape_character, local.defaults.iosxr.devices.configuration.line_default.escape_character, null)
  session_timeout             = try(local.device_config[each.value.name].line_default.session_timeout, local.defaults.iosxr.devices.configuration.line_default.session_timeout, null)
  session_timeout_output      = try(local.device_config[each.value.name].line_default.session_timeout_output, local.defaults.iosxr.devices.configuration.line_default.session_timeout_output, null)
  transport_input_ssh         = try(local.device_config[each.value.name].line_default.transport_input_ssh, local.defaults.iosxr.devices.configuration.line_default.transport_input_ssh, null)
  transport_output_ssh_telnet = try(local.device_config[each.value.name].line_default.transport_output_ssh_telnet, local.defaults.iosxr.devices.configuration.line_default.transport_output_ssh_telnet, null)
  transport_preferred_ssh     = try(local.device_config[each.value.name].line_default.transport_preferred_ssh, local.defaults.iosxr.devices.configuration.line_default.transport_preferred_ssh, null)
  session_limit               = try(local.device_config[each.value.name].line_default.session_limit, local.defaults.iosxr.devices.configuration.line_default.session_limit, null)
  cli_whitespace_completion   = try(local.device_config[each.value.name].line_default.cli_whitespace_completion, local.defaults.iosxr.devices.configuration.line_default.cli_whitespace_completion, null)
  secret_encrypted            = try(local.device_config[each.value.name].line_default.secret_encrypted, local.defaults.iosxr.devices.configuration.line_default.secret_encrypted, null)
  password_encrypted          = try(local.device_config[each.value.name].line_default.password_encrypted, local.defaults.iosxr.devices.configuration.line_default.password_encrypted, null)
  timeout_login_response      = try(local.device_config[each.value.name].line_default.timeout_login_response, local.defaults.iosxr.devices.configuration.line_default.timeout_login_response, null)
  exec_timeout_minutes        = try(local.device_config[each.value.name].line_default.exec_timeout_minutes, local.defaults.iosxr.devices.configuration.line_default.exec_timeout_minutes, null)
  exec_timeout_seconds        = try(local.device_config[each.value.name].line_default.exec_timeout_seconds, local.defaults.iosxr.devices.configuration.line_default.exec_timeout_seconds, null)
  absolute_timeout            = try(local.device_config[each.value.name].line_default.absolute_timeout, local.defaults.iosxr.devices.configuration.line_default.absolute_timeout, null)
  width                       = try(local.device_config[each.value.name].line_default.width, local.defaults.iosxr.devices.configuration.line_default.width, null)
  length                      = try(local.device_config[each.value.name].line_default.length, local.defaults.iosxr.devices.configuration.line_default.length, null)
  timestamp_disable           = try(local.device_config[each.value.name].line_default.timestamp_disable, local.defaults.iosxr.devices.configuration.line_default.timestamp_disable, null)
  pager                       = try(local.device_config[each.value.name].line_default.pager, local.defaults.iosxr.devices.configuration.line_default.pager, null)
  telnet_transparent          = try(local.device_config[each.value.name].line_default.telnet_transparent, local.defaults.iosxr.devices.configuration.line_default.telnet_transparent, null)
  accounting_commands         = try(local.device_config[each.value.name].line_default.accounting_commands, local.defaults.iosxr.devices.configuration.line_default.accounting_commands, null)
  accounting_exec             = try(local.device_config[each.value.name].line_default.accounting_exec, local.defaults.iosxr.devices.configuration.line_default.accounting_exec, null)
  authorization_commands      = try(local.device_config[each.value.name].line_default.authorization_commands, local.defaults.iosxr.devices.configuration.line_default.authorization_commands, null)
  authorization_eventmanager  = try(local.device_config[each.value.name].line_default.authorization_eventmanager, local.defaults.iosxr.devices.configuration.line_default.authorization_eventmanager, null)
  authorization_exec          = try(local.device_config[each.value.name].line_default.authorization_exec, local.defaults.iosxr.devices.configuration.line_default.authorization_exec, null)
  login_authentication        = try(local.device_config[each.value.name].line_default.login_authentication, local.defaults.iosxr.devices.configuration.line_default.login_authentication, null)
  transport_input_all         = try(local.device_config[each.value.name].line_default.transport_input_all, local.defaults.iosxr.devices.configuration.line_default.transport_input_all, null)
  transport_input_none        = try(local.device_config[each.value.name].line_default.transport_input_none, local.defaults.iosxr.devices.configuration.line_default.transport_input_none, null)
  transport_input_ssh_telnet  = try(local.device_config[each.value.name].line_default.transport_input_ssh_telnet, local.defaults.iosxr.devices.configuration.line_default.transport_input_ssh_telnet, null)
  transport_input_telnet      = try(local.device_config[each.value.name].line_default.transport_input_telnet, local.defaults.iosxr.devices.configuration.line_default.transport_input_telnet, null)
  transport_output_all        = try(local.device_config[each.value.name].line_default.transport_output_all, local.defaults.iosxr.devices.configuration.line_default.transport_output_all, null)
  transport_output_none       = try(local.device_config[each.value.name].line_default.transport_output_none, local.defaults.iosxr.devices.configuration.line_default.transport_output_none, null)
  transport_output_ssh        = try(local.device_config[each.value.name].line_default.transport_output_ssh, local.defaults.iosxr.devices.configuration.line_default.transport_output_ssh, null)
  transport_output_telnet     = try(local.device_config[each.value.name].line_default.transport_output_telnet, local.defaults.iosxr.devices.configuration.line_default.transport_output_telnet, null)
  transport_preferred_none    = try(local.device_config[each.value.name].line_default.transport_preferred_none, local.defaults.iosxr.devices.configuration.line_default.transport_preferred_none, null)
  transport_preferred_telnet  = try(local.device_config[each.value.name].line_default.transport_preferred_telnet, local.defaults.iosxr.devices.configuration.line_default.transport_preferred_telnet, null)
  users_group = try(length(local.device_config[each.value.name].line_default.users_group) == 0, true) ? null : [
    for group in local.device_config[each.value.name].line_default.users_group : {
      group_name = try(group.group_name, local.defaults.iosxr.devices.configuration.line_default.users_group.group_name, null)
    }
  ]
}
