resource "iosxr_aaa" "aaa" {
  for_each = { for device in local.devices : device.name => device if try(local.device_config[device.name].aaa, null) != null || try(local.defaults.iosxr.devices.configuration.aaa, null) != null }
  device   = each.value.name

  default_taskgroup = try(local.device_config[each.value.name].aaa.default_taskgroup, local.defaults.iosxr.devices.configuration.aaa.default_taskgroup, null)
  banner_login      = try(local.device_config[each.value.name].aaa.banner_login, local.defaults.iosxr.devices.configuration.aaa.banner_login, null)

  radius_server_groups = try(length(local.device_config[each.value.name].aaa.radius_server_groups) == 0, true) ? null : [
    for rsg in local.device_config[each.value.name].aaa.radius_server_groups : {
      group_name = try(rsg.group_name, null)
      servers = try(length(rsg.servers) == 0, true) ? null : [
        for s in rsg.servers : {
          order     = try(s.order, null)
          address   = try(s.address, null)
          auth_port = try(s.auth_port, null)
          acct_port = try(s.acct_port, null)
        }
      ]
      load_balance_method_least_outstanding_batch_size              = try(rsg.load_balance_method_least_outstanding_batch_size, null)
      load_balance_method_least_outstanding                         = try(rsg.load_balance_method_least_outstanding, null)
      load_balance_method_least_outstanding_ignore_preferred_server = try(rsg.load_balance_method_least_outstanding_ignore_preferred_server, null)
      deadtime                                                      = try(rsg.deadtime, null)
      throttle_access                                               = try(rsg.throttle_access, null)
      throttle_access_timeout                                       = try(rsg.throttle_access_timeout, null)
      throttle_accounting                                           = try(rsg.throttle_accounting, null)
      server_privates = try(length(rsg.server_privates) == 0, true) ? null : [
        for sp in rsg.server_privates : {
          order            = try(sp.order, null)
          address          = try(sp.address, null)
          auth_port        = try(sp.auth_port, null)
          acct_port        = try(sp.acct_port, null)
          key_type_6       = try(sp.key_type_6, null)
          key_type_7       = try(sp.key_type_7, null)
          timeout          = try(sp.timeout, null)
          retransmit       = try(sp.retransmit, null)
          test_username    = try(sp.test_username, null)
          idle_time        = try(sp.idle_time, null)
          ignore_auth_port = try(sp.ignore_auth_port, null)
          ignore_acct_port = try(sp.ignore_acct_port, null)
        }
      ]
      vrf                                         = try(rsg.vrf, null)
      source_interface                            = try(rsg.source_interface, null)
      authorization_request_accept                = try(rsg.authorization_request_accept, null)
      authorization_request_reject                = try(rsg.authorization_request_reject, null)
      authorization_request_radius_attribute_list = try(rsg.authorization_request_radius_attribute_list, null)
      authorization_reply_accept                  = try(rsg.authorization_reply_accept, null)
      authorization_reply_reject                  = try(rsg.authorization_reply_reject, null)
      authorization_reply_radius_attribute_list   = try(rsg.authorization_reply_radius_attribute_list, null)
      accounting_request_accept                   = try(rsg.accounting_request_accept, null)
      accounting_request_reject                   = try(rsg.accounting_request_reject, null)
      accounting_request_radius_attribute_list    = try(rsg.accounting_request_radius_attribute_list, null)
      accounting_reply_accept                     = try(rsg.accounting_reply_accept, null)
      accounting_reply_reject                     = try(rsg.accounting_reply_reject, null)
      accounting_reply_radius_attribute_list      = try(rsg.accounting_reply_radius_attribute_list, null)
    }
  ]

  server_radius_dynamic_author_port              = try(local.device_config[each.value.name].aaa.server_radius_dynamic_author_port, local.defaults.iosxr.devices.configuration.aaa.server_radius_dynamic_author_port, null)
  server_radius_dynamic_author_ignore_server_key = try(local.device_config[each.value.name].aaa.server_radius_dynamic_author_ignore_server_key, local.defaults.iosxr.devices.configuration.aaa.server_radius_dynamic_author_ignore_server_key, null)
  server_radius_dynamic_author_server_key_type_6 = try(local.device_config[each.value.name].aaa.server_radius_dynamic_author_server_key_type_6, local.defaults.iosxr.devices.configuration.aaa.server_radius_dynamic_author_server_key_type_6, null)
  server_radius_dynamic_author_server_key_type_7 = try(local.device_config[each.value.name].aaa.server_radius_dynamic_author_server_key_type_7, local.defaults.iosxr.devices.configuration.aaa.server_radius_dynamic_author_server_key_type_7, null)

  server_radius_dynamic_author_clients = try(length(local.device_config[each.value.name].aaa.server_radius_dynamic_author_clients) == 0, true) ? null : [
    for c in local.device_config[each.value.name].aaa.server_radius_dynamic_author_clients : {
      address           = try(c.address, null)
      vrf               = try(c.vrf, null)
      server_key_type_6 = try(c.server_key_type_6, null)
      server_key_type_7 = try(c.server_key_type_7, null)
    }
  ]

  tacacs_server_groups = try(length(local.device_config[each.value.name].aaa.tacacs_server_groups) == 0, true) ? null : [
    for tsg in local.device_config[each.value.name].aaa.tacacs_server_groups : {
      group_name = try(tsg.group_name, null)
      servers = try(length(tsg.servers) == 0, true) ? null : [
        for s in tsg.servers : {
          order   = try(s.order, null)
          address = try(s.address, null)
        }
      ]
      vrf           = try(tsg.vrf, null)
      holddown_time = try(tsg.holddown_time, null)
      server_privates = try(length(tsg.server_privates) == 0, true) ? null : [
        for sp in tsg.server_privates : {
          order                          = try(sp.order, null)
          address                        = try(sp.address, null)
          port                           = try(sp.port, null)
          key_type_6                     = try(sp.key_type_6, null)
          key_type_7                     = try(sp.key_type_7, null)
          single_connection              = try(sp.single_connection, null)
          single_connection_idle_timeout = try(sp.single_connection_idle_timeout, null)
          timeout                        = try(sp.timeout, null)
          holddown_time                  = try(sp.holddown_time, null)
        }
      ]
    }
  ]

  usernames = try(length(local.device_config[each.value.name].aaa.usernames) == 0, true) ? null : [
    for u in local.device_config[each.value.name].aaa.usernames : {
      order                 = try(u.order, null)
      name                  = try(u.name, null)
      secret_type_8         = try(u.secret_type_8, null)
      secret_type_9         = try(u.secret_type_9, null)
      secret_type_10        = try(u.secret_type_10, null)
      directory             = try(u.directory, null)
      shell_type            = try(u.shell_type, null)
      policy                = try(u.policy, null)
      login_history_enable  = try(u.login_history_enable, null)
      login_history_disable = try(u.login_history_disable, null)
      group_root_lr         = try(u.group_root_lr, null)
      group_sysadmin        = try(u.group_sysadmin, null)
      group_netadmin        = try(u.group_netadmin, null)
      group_serviceadmin    = try(u.group_serviceadmin, null)
      group_operator        = try(u.group_operator, null)
      group_cisco_support   = try(u.group_cisco_support, null)
      group_maintenance     = try(u.group_maintenance, null)
      group_provisioning    = try(u.group_provisioning, null)
      group_retrieve        = try(u.group_retrieve, null)
      group_read_only_tg    = try(u.group_read_only_tg, null)
      user_groups = try(length(u.user_groups) == 0, true) ? null : [
        for ug in u.user_groups : {
          group_name = try(ug.group_name, null)
        }
      ]
    }
  ]

  taskgroups = try(length(local.device_config[each.value.name].aaa.taskgroups) == 0, true) ? null : [
    for tg in local.device_config[each.value.name].aaa.taskgroups : {
      group_name                      = try(tg.group_name, null)
      description                     = try(tg.description, null)
      task_read_bgp                   = try(tg.task_read_bgp, null)
      task_read_ospf                  = try(tg.task_read_ospf, null)
      task_read_hsrp                  = try(tg.task_read_hsrp, null)
      task_read_isis                  = try(tg.task_read_isis, null)
      task_read_route_map             = try(tg.task_read_route_map, null)
      task_read_route_policy          = try(tg.task_read_route_policy, null)
      task_read_static                = try(tg.task_read_static, null)
      task_read_vrrp                  = try(tg.task_read_vrrp, null)
      task_read_cef                   = try(tg.task_read_cef, null)
      task_read_lpts                  = try(tg.task_read_lpts, null)
      task_read_ipv4                  = try(tg.task_read_ipv4, null)
      task_read_rib                   = try(tg.task_read_rib, null)
      task_read_multicast             = try(tg.task_read_multicast, null)
      task_read_mpls_te               = try(tg.task_read_mpls_te, null)
      task_read_mpls_ldp              = try(tg.task_read_mpls_ldp, null)
      task_read_mpls_static           = try(tg.task_read_mpls_static, null)
      task_read_ouni                  = try(tg.task_read_ouni, null)
      task_read_fabric                = try(tg.task_read_fabric, null)
      task_read_bundle                = try(tg.task_read_bundle, null)
      task_read_network               = try(tg.task_read_network, null)
      task_read_transport             = try(tg.task_read_transport, null)
      task_read_ppp                   = try(tg.task_read_ppp, null)
      task_read_hdlc                  = try(tg.task_read_hdlc, null)
      task_read_pos_dpt               = try(tg.task_read_pos_dpt, null)
      task_read_sonet_sdh             = try(tg.task_read_sonet_sdh, null)
      task_read_dwdm                  = try(tg.task_read_dwdm, null)
      task_read_tunnel                = try(tg.task_read_tunnel, null)
      task_read_vlan                  = try(tg.task_read_vlan, null)
      task_read_qos                   = try(tg.task_read_qos, null)
      task_read_acl                   = try(tg.task_read_acl, null)
      task_read_aaa                   = try(tg.task_read_aaa, null)
      task_read_crypto                = try(tg.task_read_crypto, null)
      task_read_snmp                  = try(tg.task_read_snmp, null)
      task_read_config_mgmt           = try(tg.task_read_config_mgmt, null)
      task_read_config_services       = try(tg.task_read_config_services, null)
      task_read_host_services         = try(tg.task_read_host_services, null)
      task_read_boot                  = try(tg.task_read_boot, null)
      task_read_fault_mgr             = try(tg.task_read_fault_mgr, null)
      task_read_filesystem            = try(tg.task_read_filesystem, null)
      task_read_interface             = try(tg.task_read_interface, null)
      task_read_ip_services           = try(tg.task_read_ip_services, null)
      task_read_pkg_mgmt              = try(tg.task_read_pkg_mgmt, null)
      task_read_system                = try(tg.task_read_system, null)
      task_read_tty_access            = try(tg.task_read_tty_access, null)
      task_read_basic_services        = try(tg.task_read_basic_services, null)
      task_read_cdp                   = try(tg.task_read_cdp, null)
      task_read_diag                  = try(tg.task_read_diag, null)
      task_read_ext_access            = try(tg.task_read_ext_access, null)
      task_read_bcdl                  = try(tg.task_read_bcdl, null)
      task_read_sysmgr                = try(tg.task_read_sysmgr, null)
      task_read_logging               = try(tg.task_read_logging, null)
      task_read_netflow               = try(tg.task_read_netflow, null)
      task_read_drivers               = try(tg.task_read_drivers, null)
      task_read_fr                    = try(tg.task_read_fr, null)
      task_read_monitor               = try(tg.task_read_monitor, null)
      task_read_inventory             = try(tg.task_read_inventory, null)
      task_read_ipv6                  = try(tg.task_read_ipv6, null)
      task_read_admin                 = try(tg.task_read_admin, null)
      task_read_atm                   = try(tg.task_read_atm, null)
      task_read_bfd                   = try(tg.task_read_bfd, null)
      task_read_rip                   = try(tg.task_read_rip, null)
      task_read_eigrp                 = try(tg.task_read_eigrp, null)
      task_read_sbc                   = try(tg.task_read_sbc, null)
      task_read_firewall              = try(tg.task_read_firewall, null)
      task_read_l2vpn                 = try(tg.task_read_l2vpn, null)
      task_read_ethernet_services     = try(tg.task_read_ethernet_services, null)
      task_read_eem                   = try(tg.task_read_eem, null)
      task_read_li                    = try(tg.task_read_li, null)
      task_read_ancp                  = try(tg.task_read_ancp, null)
      task_read_cgn                   = try(tg.task_read_cgn, null)
      task_read_call_home             = try(tg.task_read_call_home, null)
      task_read_rcmd                  = try(tg.task_read_rcmd, null)
      task_read_vpdn                  = try(tg.task_read_vpdn, null)
      task_read_nps                   = try(tg.task_read_nps, null)
      task_read_lisp                  = try(tg.task_read_lisp, null)
      task_read_pbr                   = try(tg.task_read_pbr, null)
      task_read_otn                   = try(tg.task_read_otn, null)
      task_read_nacm                  = try(tg.task_read_nacm, null)
      task_read_plat_mgr              = try(tg.task_read_plat_mgr, null)
      task_read_cpri                  = try(tg.task_read_cpri, null)
      task_read_lldp                  = try(tg.task_read_lldp, null)
      task_read_l2rib                 = try(tg.task_read_l2rib, null)
      task_read_dossier               = try(tg.task_read_dossier, null)
      task_read_fti                   = try(tg.task_read_fti, null)
      task_read_fc                    = try(tg.task_read_fc, null)
      task_write_bgp                  = try(tg.task_write_bgp, null)
      task_write_ospf                 = try(tg.task_write_ospf, null)
      task_write_hsrp                 = try(tg.task_write_hsrp, null)
      task_write_isis                 = try(tg.task_write_isis, null)
      task_write_route_map            = try(tg.task_write_route_map, null)
      task_write_route_policy         = try(tg.task_write_route_policy, null)
      task_write_static               = try(tg.task_write_static, null)
      task_write_vrrp                 = try(tg.task_write_vrrp, null)
      task_write_cef                  = try(tg.task_write_cef, null)
      task_write_lpts                 = try(tg.task_write_lpts, null)
      task_write_ipv4                 = try(tg.task_write_ipv4, null)
      task_write_rib                  = try(tg.task_write_rib, null)
      task_write_multicast            = try(tg.task_write_multicast, null)
      task_write_mpls_te              = try(tg.task_write_mpls_te, null)
      task_write_mpls_ldp             = try(tg.task_write_mpls_ldp, null)
      task_write_mpls_static          = try(tg.task_write_mpls_static, null)
      task_write_ouni                 = try(tg.task_write_ouni, null)
      task_write_fabric               = try(tg.task_write_fabric, null)
      task_write_bundle               = try(tg.task_write_bundle, null)
      task_write_network              = try(tg.task_write_network, null)
      task_write_transport            = try(tg.task_write_transport, null)
      task_write_ppp                  = try(tg.task_write_ppp, null)
      task_write_hdlc                 = try(tg.task_write_hdlc, null)
      task_write_pos_dpt              = try(tg.task_write_pos_dpt, null)
      task_write_sonet_sdh            = try(tg.task_write_sonet_sdh, null)
      task_write_dwdm                 = try(tg.task_write_dwdm, null)
      task_write_tunnel               = try(tg.task_write_tunnel, null)
      task_write_vlan                 = try(tg.task_write_vlan, null)
      task_write_qos                  = try(tg.task_write_qos, null)
      task_write_acl                  = try(tg.task_write_acl, null)
      task_write_aaa                  = try(tg.task_write_aaa, null)
      task_write_crypto               = try(tg.task_write_crypto, null)
      task_write_snmp                 = try(tg.task_write_snmp, null)
      task_write_config_mgmt          = try(tg.task_write_config_mgmt, null)
      task_write_config_services      = try(tg.task_write_config_services, null)
      task_write_host_services        = try(tg.task_write_host_services, null)
      task_write_boot                 = try(tg.task_write_boot, null)
      task_write_fault_mgr            = try(tg.task_write_fault_mgr, null)
      task_write_filesystem           = try(tg.task_write_filesystem, null)
      task_write_interface            = try(tg.task_write_interface, null)
      task_write_ip_services          = try(tg.task_write_ip_services, null)
      task_write_pkg_mgmt             = try(tg.task_write_pkg_mgmt, null)
      task_write_system               = try(tg.task_write_system, null)
      task_write_tty_access           = try(tg.task_write_tty_access, null)
      task_write_basic_services       = try(tg.task_write_basic_services, null)
      task_write_cdp                  = try(tg.task_write_cdp, null)
      task_write_diag                 = try(tg.task_write_diag, null)
      task_write_ext_access           = try(tg.task_write_ext_access, null)
      task_write_bcdl                 = try(tg.task_write_bcdl, null)
      task_write_sysmgr               = try(tg.task_write_sysmgr, null)
      task_write_logging              = try(tg.task_write_logging, null)
      task_write_netflow              = try(tg.task_write_netflow, null)
      task_write_drivers              = try(tg.task_write_drivers, null)
      task_write_fr                   = try(tg.task_write_fr, null)
      task_write_monitor              = try(tg.task_write_monitor, null)
      task_write_inventory            = try(tg.task_write_inventory, null)
      task_write_ipv6                 = try(tg.task_write_ipv6, null)
      task_write_admin                = try(tg.task_write_admin, null)
      task_write_atm                  = try(tg.task_write_atm, null)
      task_write_bfd                  = try(tg.task_write_bfd, null)
      task_write_rip                  = try(tg.task_write_rip, null)
      task_write_eigrp                = try(tg.task_write_eigrp, null)
      task_write_sbc                  = try(tg.task_write_sbc, null)
      task_write_firewall             = try(tg.task_write_firewall, null)
      task_write_l2vpn                = try(tg.task_write_l2vpn, null)
      task_write_ethernet_services    = try(tg.task_write_ethernet_services, null)
      task_write_eem                  = try(tg.task_write_eem, null)
      task_write_li                   = try(tg.task_write_li, null)
      task_write_ancp                 = try(tg.task_write_ancp, null)
      task_write_cgn                  = try(tg.task_write_cgn, null)
      task_write_call_home            = try(tg.task_write_call_home, null)
      task_write_rcmd                 = try(tg.task_write_rcmd, null)
      task_write_vpdn                 = try(tg.task_write_vpdn, null)
      task_write_nps                  = try(tg.task_write_nps, null)
      task_write_lisp                 = try(tg.task_write_lisp, null)
      task_write_pbr                  = try(tg.task_write_pbr, null)
      task_write_otn                  = try(tg.task_write_otn, null)
      task_write_nacm                 = try(tg.task_write_nacm, null)
      task_write_plat_mgr             = try(tg.task_write_plat_mgr, null)
      task_write_cpri                 = try(tg.task_write_cpri, null)
      task_write_lldp                 = try(tg.task_write_lldp, null)
      task_write_l2rib                = try(tg.task_write_l2rib, null)
      task_write_dossier              = try(tg.task_write_dossier, null)
      task_write_fti                  = try(tg.task_write_fti, null)
      task_write_fc                   = try(tg.task_write_fc, null)
      task_execute_bgp                = try(tg.task_execute_bgp, null)
      task_execute_ospf               = try(tg.task_execute_ospf, null)
      task_execute_hsrp               = try(tg.task_execute_hsrp, null)
      task_execute_isis               = try(tg.task_execute_isis, null)
      task_execute_route_map          = try(tg.task_execute_route_map, null)
      task_execute_route_policy       = try(tg.task_execute_route_policy, null)
      task_execute_static             = try(tg.task_execute_static, null)
      task_execute_vrrp               = try(tg.task_execute_vrrp, null)
      task_execute_cef                = try(tg.task_execute_cef, null)
      task_execute_lpts               = try(tg.task_execute_lpts, null)
      task_execute_ipv4               = try(tg.task_execute_ipv4, null)
      task_execute_rib                = try(tg.task_execute_rib, null)
      task_execute_multicast          = try(tg.task_execute_multicast, null)
      task_execute_mpls_te            = try(tg.task_execute_mpls_te, null)
      task_execute_mpls_ldp           = try(tg.task_execute_mpls_ldp, null)
      task_execute_mpls_static        = try(tg.task_execute_mpls_static, null)
      task_execute_ouni               = try(tg.task_execute_ouni, null)
      task_execute_fabric             = try(tg.task_execute_fabric, null)
      task_execute_bundle             = try(tg.task_execute_bundle, null)
      task_execute_network            = try(tg.task_execute_network, null)
      task_execute_transport          = try(tg.task_execute_transport, null)
      task_execute_ppp                = try(tg.task_execute_ppp, null)
      task_execute_hdlc               = try(tg.task_execute_hdlc, null)
      task_execute_pos_dpt            = try(tg.task_execute_pos_dpt, null)
      task_execute_sonet_sdh          = try(tg.task_execute_sonet_sdh, null)
      task_execute_dwdm               = try(tg.task_execute_dwdm, null)
      task_execute_tunnel             = try(tg.task_execute_tunnel, null)
      task_execute_vlan               = try(tg.task_execute_vlan, null)
      task_execute_qos                = try(tg.task_execute_qos, null)
      task_execute_acl                = try(tg.task_execute_acl, null)
      task_execute_aaa                = try(tg.task_execute_aaa, null)
      task_execute_crypto             = try(tg.task_execute_crypto, null)
      task_execute_snmp               = try(tg.task_execute_snmp, null)
      task_execute_config_mgmt        = try(tg.task_execute_config_mgmt, null)
      task_execute_config_services    = try(tg.task_execute_config_services, null)
      task_execute_host_services      = try(tg.task_execute_host_services, null)
      task_execute_boot               = try(tg.task_execute_boot, null)
      task_execute_fault_mgr          = try(tg.task_execute_fault_mgr, null)
      task_execute_filesystem         = try(tg.task_execute_filesystem, null)
      task_execute_interface          = try(tg.task_execute_interface, null)
      task_execute_ip_services        = try(tg.task_execute_ip_services, null)
      task_execute_pkg_mgmt           = try(tg.task_execute_pkg_mgmt, null)
      task_execute_system             = try(tg.task_execute_system, null)
      task_execute_tty_access         = try(tg.task_execute_tty_access, null)
      task_execute_basic_services     = try(tg.task_execute_basic_services, null)
      task_execute_cdp                = try(tg.task_execute_cdp, null)
      task_execute_diag               = try(tg.task_execute_diag, null)
      task_execute_ext_access         = try(tg.task_execute_ext_access, null)
      task_execute_bcdl               = try(tg.task_execute_bcdl, null)
      task_execute_sysmgr             = try(tg.task_execute_sysmgr, null)
      task_execute_logging            = try(tg.task_execute_logging, null)
      task_execute_netflow            = try(tg.task_execute_netflow, null)
      task_execute_drivers            = try(tg.task_execute_drivers, null)
      task_execute_fr                 = try(tg.task_execute_fr, null)
      task_execute_monitor            = try(tg.task_execute_monitor, null)
      task_execute_inventory          = try(tg.task_execute_inventory, null)
      task_execute_ipv6               = try(tg.task_execute_ipv6, null)
      task_execute_admin              = try(tg.task_execute_admin, null)
      task_execute_atm                = try(tg.task_execute_atm, null)
      task_execute_bfd                = try(tg.task_execute_bfd, null)
      task_execute_rip                = try(tg.task_execute_rip, null)
      task_execute_eigrp              = try(tg.task_execute_eigrp, null)
      task_execute_sbc                = try(tg.task_execute_sbc, null)
      task_execute_firewall           = try(tg.task_execute_firewall, null)
      task_execute_l2vpn              = try(tg.task_execute_l2vpn, null)
      task_execute_ethernet_services  = try(tg.task_execute_ethernet_services, null)
      task_execute_eem                = try(tg.task_execute_eem, null)
      task_execute_li                 = try(tg.task_execute_li, null)
      task_execute_ancp               = try(tg.task_execute_ancp, null)
      task_execute_cgn                = try(tg.task_execute_cgn, null)
      task_execute_call_home          = try(tg.task_execute_call_home, null)
      task_execute_rcmd               = try(tg.task_execute_rcmd, null)
      task_execute_vpdn               = try(tg.task_execute_vpdn, null)
      task_execute_nps                = try(tg.task_execute_nps, null)
      task_execute_lisp               = try(tg.task_execute_lisp, null)
      task_execute_pbr                = try(tg.task_execute_pbr, null)
      task_execute_otn                = try(tg.task_execute_otn, null)
      task_execute_nacm               = try(tg.task_execute_nacm, null)
      task_execute_plat_mgr           = try(tg.task_execute_plat_mgr, null)
      task_execute_cpri               = try(tg.task_execute_cpri, null)
      task_execute_lldp               = try(tg.task_execute_lldp, null)
      task_execute_l2rib              = try(tg.task_execute_l2rib, null)
      task_execute_dossier            = try(tg.task_execute_dossier, null)
      task_execute_fti                = try(tg.task_execute_fti, null)
      task_execute_fc                 = try(tg.task_execute_fc, null)
      task_debug_bgp                  = try(tg.task_debug_bgp, null)
      task_debug_ospf                 = try(tg.task_debug_ospf, null)
      task_debug_hsrp                 = try(tg.task_debug_hsrp, null)
      task_debug_isis                 = try(tg.task_debug_isis, null)
      task_debug_route_map            = try(tg.task_debug_route_map, null)
      task_debug_route_policy         = try(tg.task_debug_route_policy, null)
      task_debug_static               = try(tg.task_debug_static, null)
      task_debug_vrrp                 = try(tg.task_debug_vrrp, null)
      task_debug_cef                  = try(tg.task_debug_cef, null)
      task_debug_lpts                 = try(tg.task_debug_lpts, null)
      task_debug_ipv4                 = try(tg.task_debug_ipv4, null)
      task_debug_rib                  = try(tg.task_debug_rib, null)
      task_debug_multicast            = try(tg.task_debug_multicast, null)
      task_debug_mpls_te              = try(tg.task_debug_mpls_te, null)
      task_debug_mpls_ldp             = try(tg.task_debug_mpls_ldp, null)
      task_debug_mpls_static          = try(tg.task_debug_mpls_static, null)
      task_debug_ouni                 = try(tg.task_debug_ouni, null)
      task_debug_fabric               = try(tg.task_debug_fabric, null)
      task_debug_bundle               = try(tg.task_debug_bundle, null)
      task_debug_network              = try(tg.task_debug_network, null)
      task_debug_transport            = try(tg.task_debug_transport, null)
      task_debug_ppp                  = try(tg.task_debug_ppp, null)
      task_debug_hdlc                 = try(tg.task_debug_hdlc, null)
      task_debug_pos_dpt              = try(tg.task_debug_pos_dpt, null)
      task_debug_sonet_sdh            = try(tg.task_debug_sonet_sdh, null)
      task_debug_dwdm                 = try(tg.task_debug_dwdm, null)
      task_debug_tunnel               = try(tg.task_debug_tunnel, null)
      task_debug_vlan                 = try(tg.task_debug_vlan, null)
      task_debug_qos                  = try(tg.task_debug_qos, null)
      task_debug_acl                  = try(tg.task_debug_acl, null)
      task_debug_aaa                  = try(tg.task_debug_aaa, null)
      task_debug_crypto               = try(tg.task_debug_crypto, null)
      task_debug_snmp                 = try(tg.task_debug_snmp, null)
      task_debug_config_mgmt          = try(tg.task_debug_config_mgmt, null)
      task_debug_config_services      = try(tg.task_debug_config_services, null)
      task_debug_host_services        = try(tg.task_debug_host_services, null)
      task_debug_boot                 = try(tg.task_debug_boot, null)
      task_debug_fault_mgr            = try(tg.task_debug_fault_mgr, null)
      task_debug_filesystem           = try(tg.task_debug_filesystem, null)
      task_debug_interface            = try(tg.task_debug_interface, null)
      task_debug_ip_services          = try(tg.task_debug_ip_services, null)
      task_debug_pkg_mgmt             = try(tg.task_debug_pkg_mgmt, null)
      task_debug_system               = try(tg.task_debug_system, null)
      task_debug_tty_access           = try(tg.task_debug_tty_access, null)
      task_debug_basic_services       = try(tg.task_debug_basic_services, null)
      task_debug_cdp                  = try(tg.task_debug_cdp, null)
      task_debug_diag                 = try(tg.task_debug_diag, null)
      task_debug_ext_access           = try(tg.task_debug_ext_access, null)
      task_debug_bcdl                 = try(tg.task_debug_bcdl, null)
      task_debug_sysmgr               = try(tg.task_debug_sysmgr, null)
      task_debug_logging              = try(tg.task_debug_logging, null)
      task_debug_netflow              = try(tg.task_debug_netflow, null)
      task_debug_drivers              = try(tg.task_debug_drivers, null)
      task_debug_fr                   = try(tg.task_debug_fr, null)
      task_debug_monitor              = try(tg.task_debug_monitor, null)
      task_debug_inventory            = try(tg.task_debug_inventory, null)
      task_debug_ipv6                 = try(tg.task_debug_ipv6, null)
      task_debug_admin                = try(tg.task_debug_admin, null)
      task_debug_atm                  = try(tg.task_debug_atm, null)
      task_debug_bfd                  = try(tg.task_debug_bfd, null)
      task_debug_rip                  = try(tg.task_debug_rip, null)
      task_debug_eigrp                = try(tg.task_debug_eigrp, null)
      task_debug_sbc                  = try(tg.task_debug_sbc, null)
      task_debug_firewall             = try(tg.task_debug_firewall, null)
      task_debug_l2vpn                = try(tg.task_debug_l2vpn, null)
      task_debug_ethernet_services    = try(tg.task_debug_ethernet_services, null)
      task_debug_eem                  = try(tg.task_debug_eem, null)
      task_debug_li                   = try(tg.task_debug_li, null)
      task_debug_ancp                 = try(tg.task_debug_ancp, null)
      task_debug_cgn                  = try(tg.task_debug_cgn, null)
      task_debug_call_home            = try(tg.task_debug_call_home, null)
      task_debug_rcmd                 = try(tg.task_debug_rcmd, null)
      task_debug_vpdn                 = try(tg.task_debug_vpdn, null)
      task_debug_nps                  = try(tg.task_debug_nps, null)
      task_debug_lisp                 = try(tg.task_debug_lisp, null)
      task_debug_pbr                  = try(tg.task_debug_pbr, null)
      task_debug_otn                  = try(tg.task_debug_otn, null)
      task_debug_nacm                 = try(tg.task_debug_nacm, null)
      task_debug_plat_mgr             = try(tg.task_debug_plat_mgr, null)
      task_debug_cpri                 = try(tg.task_debug_cpri, null)
      task_debug_lldp                 = try(tg.task_debug_lldp, null)
      task_debug_l2rib                = try(tg.task_debug_l2rib, null)
      task_debug_dossier              = try(tg.task_debug_dossier, null)
      task_debug_fti                  = try(tg.task_debug_fti, null)
      task_debug_fc                   = try(tg.task_debug_fc, null)
      inherit_taskgroup_root_lr       = try(tg.inherit_taskgroup_root_lr, null)
      inherit_taskgroup_netadmin      = try(tg.inherit_taskgroup_netadmin, null)
      inherit_taskgroup_sysadmin      = try(tg.inherit_taskgroup_sysadmin, null)
      inherit_taskgroup_serviceadmin  = try(tg.inherit_taskgroup_serviceadmin, null)
      inherit_taskgroup_operator      = try(tg.inherit_taskgroup_operator, null)
      inherit_taskgroup_cisco_support = try(tg.inherit_taskgroup_cisco_support, null)
      inherit_taskgroups = try(length(tg.inherit_taskgroups) == 0, true) ? null : [
        for itg in tg.inherit_taskgroups : {
          group_name = try(itg.group_name, null)
        }
      ]
    }
  ]

  usergroups = try(length(local.device_config[each.value.name].aaa.usergroups) == 0, true) ? null : [
    for ug in local.device_config[each.value.name].aaa.usergroups : {
      group_name              = try(ug.group_name, null)
      description             = try(ug.description, null)
      taskgroup_root_lr       = try(ug.taskgroup_root_lr, null)
      taskgroup_netadmin      = try(ug.taskgroup_netadmin, null)
      taskgroup_sysadmin      = try(ug.taskgroup_sysadmin, null)
      taskgroup_serviceadmin  = try(ug.taskgroup_serviceadmin, null)
      taskgroup_operator      = try(ug.taskgroup_operator, null)
      taskgroup_cisco_support = try(ug.taskgroup_cisco_support, null)
      taskgroup_maintenance   = try(ug.taskgroup_maintenance, null)
      taskgroup_provisioning  = try(ug.taskgroup_provisioning, null)
      taskgroup_retrieve      = try(ug.taskgroup_retrieve, null)
      taskgroup_read_only     = try(ug.taskgroup_read_only, null)
      taskgroups = try(length(ug.taskgroups) == 0, true) ? null : [
        for tg in ug.taskgroups : {
          group_name = try(tg.group_name, null)
        }
      ]
      inherit_usergroups = try(length(ug.inherit_usergroups) == 0, true) ? null : [
        for iug in ug.inherit_usergroups : {
          group_name = try(iug.group_name, null)
        }
      ]
    }
  ]
}
